### ISSUE TITLE
Improve matching skill level of review assignments

### ISSUE THREAD

**Issue by leikkisa** [LearnersGuild/prrr#131]
Improve matching project reviews with people who are closer in range to the skill level required to review the project.  Proposed approach (there may also be other good approaches!):

1) Show a list of project titles which are awaiting a review (so if there are many reviews that are the same project but multiple teams, they would all fall under the same project title).  When people are reviewing, they can get a sense based on the project title if they've done it before, or if they haven't done it if it might be within their competency level or just slightly above, instead of beyond their abilities completely.

2) Potentially show the "milestone" level of the project to help this decision making (maybe this is already part of the random assignment?).

3) If there is an issue that people will not review the harder projects, perhaps harder projects could be worth more RXP to provide further incentive.  If some projects still don't get reviewed then maybe projects which haven't been selected quickly enough can get automatically assigned to the professional reviewers, or people with high RXP (although if they're also worth more RXP, this would create a positive reinforcing feedback loop which might be undesirable).

**Comment by Anasauce** [comment]
@leikissa I think this is a great feature.

Although, I don't think we should display all of the Prrrs waiting for review. 

I would suggest adding a field to the form when you are submitting your Prrr to list the Goal you are working on and the level you are in.

Then when looking for a Prrr to review a reviewer could filter the Prrrs based by project, or by level.

This could keep a cleaner UI...and it still make sure the Prrrs are getting reviewed in the order that they were submitted.

**Comment by Anasauce** [comment]
I'm not too worried about harder projects not getting reviewed, week by week more learners are getting moved up into higher levels and wouldn't mind (actually enjoy) reviewing Prrrs on the more complex projects

**Comment by leikissa** [comment]
I like your idea!

**Comment by deadlyicon** [comment]
We definitely need some feature(s) to address this need. Next week is a bad week for this because all the partners will be at the retreat. I think we should tentatively plan to do this on the following week. Sound good?

**Comment by leikissa** [comment]
It is not urgent!  It came up during conversation so I brought it up during PSG when bringing up other Project Review woes. Thanks all.

**Comment by jason00111** [comment]
@leikissa These are really great ideas.  We need to break them up into much smaller issues.

I'd like to re-propose the original proposal, "that the PRR app offers a list of PRRs that need to be reviewed [...] so that it's easier to pick one that feels within one's ability to review".

In an earlier version, you could see all the prrrs and select which one to review.

To get us back there, it might just mean deleting a bunch of code, which is fun.

**Comment by jason00111** [comment]
@leikissa The idea about RXP is great.  Prrr is probably not the place to pursue this.  I'll find out where to make an issue.

**Comment by deadlyicon** [comment]
I always prefer to solve a problem by giving people more freedom instead of less. I think we should trash this whole blind queue thing for now and go back to a selectable list. This wont tell you what project people are working on but it will give you the means to figure that out. 

The selectable list interface and the queries for it are all somewhere in the git history of this app. If someone wants to write up a proposal for the specs, I will consider approving a team or two to work on Prrr next week while I'm at the retreat.
